server:
  port: 8004

spring:
  application:
    name: statistics-mgmt
  datasource:
    url: jdbc:postgresql://localhost:5432/auto_software_admin
    username: root
    password:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
      uri: mongodb://localhost:27017/auto_software

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true