spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auto_software_admin?currentSchema=login_mgmt
    username: root
    password:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource