server:
  port: 8002

spring:
  application:
    name: user-mgmt
  datasource:
    url: jdbc:postgresql://localhost:5432/auto_software_admin?currentSchema=user_mgmt
    username: root
    password: zjt010526_T
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true