spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.cloud.client.hostname}:${server.port}
  datasource:
    url: jdbc:postgresql://localhost:5432/auto_software_admin?currentSchema=user_mgmt
    username: root
    password:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource